import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REGISTRY_ROOT = path.resolve(__dirname, '..');
const PUBLIC_DIR = path.join(REGISTRY_ROOT, 'public/r');
const REGISTRY_JSON_PATH = path.join(REGISTRY_ROOT, 'registry.json');

async function organizeByCategory() {
  console.log('📁 Organizing registry files by category...\n');

  // Read registry.json to get category metadata
  const registry = await fs.readJson(REGISTRY_JSON_PATH);

  // Track components by category
  const componentsByCategory: Record<string, any[]> = {
    core: [],
    convex: [],
    clerk: [],
    'convex-clerk': [],
  };

  // Process each component
  for (const item of registry.items) {
    const category = item.category || 'core';
    const componentName = item.name;

    // Read the flat file generated by shadcn build
    const flatFilePath = path.join(PUBLIC_DIR, `${componentName}.json`);

    if (await fs.pathExists(flatFilePath)) {
      const componentData = await fs.readJson(flatFilePath);

      // Add category field
      componentData.category = category;

      // Write to category directory
      const categoryDir = path.join(PUBLIC_DIR, category);
      await fs.ensureDir(categoryDir);
      const categoryFilePath = path.join(categoryDir, `${componentName}.json`);
      await fs.writeJson(categoryFilePath, componentData, { spaces: 2 });

      console.log(`  ✓ Organized ${componentName} → ${category}/`);

      // Add to category index (without file content)
      componentsByCategory[category].push({
        name: item.name,
        title: item.title,
        description: item.description,
        tags: item.tags,
        dependencies: item.dependencies,
        registryDependencies: item.registryDependencies,
      });
    }
  }

  // Generate category index files
  console.log('\n📝 Generating category indexes...');
  for (const [category, components] of Object.entries(componentsByCategory)) {
    const indexPath = path.join(PUBLIC_DIR, category, 'index.json');
    await fs.ensureDir(path.dirname(indexPath));
    await fs.writeJson(indexPath, components, { spaces: 2 });
    console.log(`  ✓ Generated ${category}/index.json (${components.length} components)`);
  }

  console.log('\n✅ Category organization complete!');
}

organizeByCategory().catch((error) => {
  console.error('\n❌ Organization failed:', error.message);
  process.exit(1);
});
